title: Mehedi Khan
name: Mehedi Khan
description: "Software Engineer. Distributed Systems, ML Systems, Applied AI."
url: "https://mehedikhan.me"
baseurl: ""

author: Mehedi Khan
email: mehedi.72.khan@gmail.com
image: /assets/img/og-image.png
logo: /assets/img/og-image.png

permalink: /blogs/:title/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og-image.png
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

sass:
  style: compressed
  sourcemap: never

include:
  - .nojekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - serve.sh
  - vendor
  - node_modules
